Bump version: 0.4.12 → 0.4.13

diff --git a/bashrc/scripts/bashrc-aliases b/bashrc/scripts/bashrc-aliases
--- a/bashrc/scripts/bashrc-aliases
+++ b/bashrc/scripts/bashrc-aliases
@@ -1,362 +1,305 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC2139
-export starting="${BASH_SOURCE[0]}"
-debug.sh starting
-
-## BASHRC
-if test -n "${DARWIN}"; then
-  alias rebashrc="bashrc-upload.sh; bashrc-upgrade.sh; rebash"
-else
-  alias rebashrc="bashrc-upgrade.sh; rebash"
-fi
-
-## ATHENS
-alias athens='docker -H tcp://repo.nferx.com:2375 logs --details --follow  lumenbiomics'
-
-## BASH_IT
-if ls --color -d . &>/dev/null; then
-  alias ls="ls --color=auto"
-elif ls -G -d . &>/dev/null; then
-  alias ls='ls -G' # Compact view, show colors
-fi
-
+# /Users/j5pu/.config/rclone/rclone.conf
 # List directory contents
-alias sl=ls
-alias la='ls -AF' # Compact view, show hidden
-alias ll='ls -al'
-alias l='ls -a'
-alias l1='ls -1'
-
-alias _="sudo"
-
-## CD
-alias ..="cd .."         # Up one level
-alias ...="cd ../.."     # Up two levels
+# https://console.scaleway.com/object-storage/buckets/fr-par/pictures-documents-j5pu/explorer
+# https://www.scaleway.com/en/docs/how-to-migrate-object-storage-buckets-with-rclone/
 alias ....="cd ../../.." # Up three levels
-
-alias .b="cd '${PROJECT_BASHRC}'"
-alias .h="cd '${USERHOME}'"
-alias .i="cd '${ICLOUD}'"
-alias .l="cd '${LIBRARY}'"
-alias .m="cd '${MACDEV}'"
-alias .p="cd '${PEN}'"
-
+alias ...="cd ../.."     # Up two levels
+alias ..="cd .."         # Up one level
 alias .ansible="cd '${ANSIBLE}'"
+alias .b="cd '${PROJECT_BASHRC}'"
 alias .bash="cd '${BASH_D}'"
 alias .caches="cd '${CACHES}'"
 alias .clones="cd '${CLONES}'"
-alias .downloads="cd '${USERHOME}/Downloads'"
 alias .desktop="cd '${USERHOME}/Desktop'"
 alias .documents="cd '${USERHOME}/Documents'"
+alias .downloads="cd '${USERHOME}/Downloads'"
 alias .dropbox="cd '${DROPBOX}'"
 alias .examples="cd '${EXAMPLES}'"
 alias .files="cd '${FILES}'"
 alias .go="cd '${GOHOME}'"
+alias .h="cd '${USERHOME}'"
+alias .i="cd '${ICLOUD}'"
 alias .jetbrains="cd '${JETBRAINS}'"
 alias .keynote="cd '${KEYNOTE}'"
+alias .l="cd '${LIBRARY}'"
 alias .latest="cd '${LATEST}'"
 alias .log="cd '${LOG}'"
 alias .lumen="cd '${LUMEN}'"
+alias .m="cd '${MACDEV}'"
 alias .mobile="cd '${MOBILE}'"
 alias .numbers="cd '${NUMBERS}'"
-alias .pages="cd '${PAGES}'"
+alias .options="cd '${PYCHARM_OPTIONS}'"
+alias .p="cd '${PEN}'"
 alias .packages="cd '${PACKAGES}'"
+alias .pages="cd '${PAGES}'"
 alias .preferences="cd '${PREFS}'"
 alias .projects="cd '${PROJECTS}'"
 alias .pycharm="cd '${PYCHARM}'"
-alias .options="cd '${PYCHARM_OPTIONS}'"
 alias .repos="cd '${REPOS}'"
 alias .saved="cd '${SAVED}'"
 alias .scratches="cd '${SCRATCHES}'"
 alias .scripts="cd '${SCRIPTS}'"
 alias .servers="cd '${PACKAGES}'"
 alias .support="cd '${SUPPORT}'"
-alias .usb="cd '${USB}'"
 alias .tbot="cd '${USERHOME}/tbot'"
-
 alias .time="cd '${TIME}'"
 alias .tmp="cd /private/tmp"
 alias .tsunami="cd '${USERHOME}/tsunami'"
-
-## CLEAR
-alias c="clear"
-
-## DOCKER
-alias dprune="docker system prune --all --volumes --force"
-alias ddisk="docker system df"
-alias dinfo="docker system info"
-alias devents="docker system events"
-alias dimagesall="docker images -a"
-alias drmi="docker rmi"
-alias dpsa="docker ps -a"
-
-## GREP
-alias pgrep="pgrep -i"
-alias grep='sudo grep --color=auto'
-alias fgrep='sudo fgrep --color=auto'
-alias egrep='sudo egrep --color=auto'
-
-## MISC
-alias cp="cp -r"
-alias finder="open ." # Open current directory in Finder
-alias less='less -R'
-alias more='more -R'
-alias play="ansible-playbook"
-alias rm="sudo rm -r"
-alias rsync_d="rsync -v -a --delete-after --checksum"
-alias speedtest="wget -O /dev/null http://speed.transip.nl/100mb.bin"
-alias update="sudo softwareupdate -aiR" # Install all macOS updates and restart system
-
-## OPEN
-alias oduti="open '${FILES}/duti/developer.text'"
-alias odeudas="brctl download '${NUMBERS}/Julia - Pension Deudas y Estimaciones Lido.numbers' && open '${NUMBERS}/Julia - Pension Deudas y Estimaciones Lido.numbers'"
-alias oreembolsos="brctl download '${NUMBERS}/Reembolsos.numbers' && open '${NUMBERS}/Reembolsos.numbers'"
-alias obrew="open '${BREWFILE}'"
-alias ogem="open '${GEMFILE}'"
-alias onpm="open '${NPMFILE}'"
-alias opip="open '${REQUIREMENTS}'"
-alias oufile="open '${USERFILE}'"
-alias ogithub="'${VISUAL}' '${REPOS}/CLONES/github.repos'"
-alias oj5pu="'${VISUAL}' '${REPOS}/HOME/${GITHUB_USERNAME}.repos'"
-alias olumenbiomics="'${VISUAL}' '${REPOS}/HOME/${GITHUB_ORGANIZATION}.repos'"
-alias oatom="open '${PYCHARM_OPTIONS}/atom-icon-associations.xml'"
-alias opost="open '${JETBRAINS}/python.mio.postfixTemplates'"
-
-## PLUTIL
-alias pltoxml="plutil -convert xml1"    # This converts the existing binary plist file into XML format
-alias pltobin="plutil -convert binary1" # This changes the plist in XML back to binary format
-
-## RM
-alias cache="test -d '${CACHES}' && sudo rm -rf '${CACHES}/*' || echo 'error no cache'"
-alias saved="test -d '${CACHES}/' && sudo rm -rf '${SAVED}/*' || echo 'error no saved'"
-
-## SCALEWAY
-# https://www.scaleway.com/en/docs/how-to-migrate-object-storage-buckets-with-rclone/
-# /Users/j5pu/.config/rclone/rclone.conf
-# https://console.scaleway.com/object-storage/buckets/fr-par/pictures-documents-j5pu/explorer
-alias scalecopy="rclone copy --progress --s3-storage-class=GLACIER"
-alias scalesync="rclone sync --progress --s3-storage-class=GLACIER"
-alias scalels="rclone ls --progress --s3-storage-class=GLACIER scaleway:/"
-alias scalelsd="rclone lsd --progress --s3-storage-class=GLACIER scaleway:/"
-alias scalelsl="rclone lsl --progress --s3-storage-class=GLACIER scaleway:/"
-alias scalesize="rclone size --progress --s3-storage-class=GLACIER scaleway:/"
-alias scalemkdir="rclone mkdir --progress --s3-storage-class=GLACIER"
-alias scalermdir="rclone rmdir --progress --s3-storage-class=GLACIER"
-alias scalermdirs="rclone rmdirs --progress --s3-storage-class=GLACIER"
-alias scalepurge="rclone purge --progress --s3-storage-class=GLACIER"
-alias scaledelete="rclone delete --progress --s3-storage-class=GLACIER"
-alias scalemove="rclone move --progress --s3-storage-class=GLACIER"
-alias scalecleanup="rclone cleanup --progress --s3-storage-class=GLACIER"
-alias scalecheck="rclone check --progress --s3-storage-class=GLACIER"
-
-## SUDO
-[[ "$(uname -s)" == "Linux" ]] && alias updatedb='sudo updatedb'
-alias trash='sudo trash'
-alias rndc='sudo rndc'
-alias find='sudo find'
-alias tcptraceroute='sudo traceroute'
-alias fail2ban-client='sudo fail2ban-client'
-alias sysupgrade='sudo sysupgrade'
-alias dscl='sudo dscl'
-alias dscacheutil='sudo dscacheutil'
-alias spctl='sudo spctl'
-alias scutil='sudo scutil'
-alias xattr='sudo xattr'
-alias networksetup='sudo networksetup'
-alias chflags='sudo chflags'
-alias shutdown="sudo shutdown --no-wall"
-alias du="sudo du"
-alias df="sudo df"
-alias dd="sudo dd"
-alias swapon='sudo swapon'
-alias swapoff="sudo swapoff"
-alias disco="sudo du -sh"
-alias update="sudo apt update"
-alias install="sudo apt install"
-alias remove="sudo apt remove"
-alias upgrade="sudo apt upgrade"
-alias dist-upgrade="sudo apt dist-upgrade"
-alias autoremove="sudo apt autoremove"
-alias autoclean="sudo apt autoclean"
-alias wpa_supplicant='sudo wpa_supplicant'
-alias wpa_passphrase='sudo wpa_passphrase'
-alias dhclient='sudo dhclient'
+alias .usb="cd '${USB}'"
+alias _="sudo"
+alias a2dismod="sudo a2dismod"
 alias a2dismode='sudo a2dismode'
 alias a2dissite='sudo a2dissite'
+alias a2enmod="sudo a2enmod"
 alias a2enmode='sudo a2enmode'
 alias a2ensite='sudo a2ensite'
 alias add-apt-repository='sudo add-apt-repository'
+alias addgroup="sudo addgroup"
 alias adduser='sudo adduser'
+alias apache2="sudo apache2"
 alias apache2ctl='sudo apache2ctl'
 alias apachectl='sudo apachectl'
-alias apt='sudo apt'
+alias apt-add-repository="sudo apt-add-repository"
+alias apt-all="sudo apt update -y; sudo apt upgrade -y; sudo apt dist-upgrade -y; sudo apt autoremove -y; sudo apt autoclean -y"
 alias apt-cache='sudo apt-cache'
-alias search="sudo apt-cache search"
+alias apt-file="sudo apt-file"
 alias apt-get='sudo apt-get'
+alias apt='sudo apt'
 alias aptitude='sudo aptitude'
+alias athens='docker -H tcp://repo.nferx.com:2375 logs --details --follow  lumenbiomics'
+alias autoclean="sudo apt autoclean"
+alias automysqlbackup="sudo automysqlbackup"
+alias autoremove="sudo apt autoremove"
+alias backups="tmutil listbackups"
+alias c="clear"
+alias cache="test -d '${CACHES}' && sudo rm -rf '${CACHES}/*' || echo 'error no cache'"
 alias certbot='sudo certbot'
 alias chattr='sudo chattr'
+alias chflags='sudo chflags'
+alias chgrp="sudo chgrp"
 alias chkrootkit='sudo chkrootkit'
 alias chmod='sudo chmod'
 alias chown='sudo chown'
+alias configure-debian="sudo configure-debian"
+alias cp="cp -r"
+alias cubic="sudo cubic"
+alias date="sudo date"
+alias dd="sudo dd"
+alias ddisk="docker system df"
+alias debconf-set-selections="sudo debconf-set-selections"
+alias debconf="sudo debconf"
+alias debi="sudo debi"
+alias debuild="sudo debuild"
+alias delgroup="sudo delgroup"
+alias deluser="sudo deluser"
+alias depmod="sudo depmod"
+alias devents="docker system events"
+alias df="sudo df"
+alias dhclient='sudo dhclient'
 alias dig='sudo dig'
+alias dimagesall="docker images -a"
+alias dinfo="docker system info"
+alias disco="sudo du -sh"
+alias dist-upgrade="sudo apt dist-upgrade"
 alias dkms='sudo dkms'
 alias dlocate='sudo dlocate'
 alias dmesg='sudo dmesg'
 alias dnstop='sudo dnstop'
-alias dpkg='sudo dpkg'
 alias dpkg-reconfigure='sudo dpkg-reconfigure'
+alias dpkg-source="sudo dpkg-source"
+alias dpkg='sudo dpkg'
+alias dprune="docker system prune --all --volumes --force"
+alias dpsa="docker ps -a"
 alias drill='sudo drill'
+alias drmi="docker rmi"
+alias dscacheutil='sudo dscacheutil'
+alias dscl='sudo dscl'
+alias du="sudo du"
+alias egrep='sudo egrep --color=auto'
+alias fail2ban-client='sudo fail2ban-client'
 alias fail2ban='sudo fail2ban'
+alias fdisk="sudo fdisk"
+alias fgrep='sudo fgrep --color=auto'
 alias find='sudo find'
+alias finder="open ." # Open current directory in Finder
 alias fkill='sudo fkill'
+alias flatpak="sudo flatpak"
 alias fsck='sudo fsck'
 alias fuser='sudo fuser'
 alias getent='sudo getent'
 alias gparted='sudo gparted'
+alias grep='sudo grep --color=auto'
 alias grub-mkconfig='sudo grub-mkconfig'
 alias hostnamectl='sudo hostnamectl'
 alias htpasswd='sudo htpasswd'
+alias hwclock="sudo hwclock"
 alias ifconfig='sudo ifconfig'
+alias install="sudo apt install"
 alias ip='sudo ip'
 alias iptables='sudo iptables'
+alias iptables_save='sudo iptables_save'
 alias iw='sudo iw'
 alias journalctl='sudo journalctl'
+alias kextload="sudo kextload"
 alias kill='sudo kill'
 alias killall='sudo killall'
+alias l1='ls -1'
+alias l='ls -a'
+alias la='ls -AF' # Compact view, show hidden
+alias latest="tmutil latestbackup"
+alias less='less -R'
+alias ll='ls -al'
 alias locale-gen='sudo locale-gen'
 alias locate='sudo locate'
+alias losetup="sudo losetup"
+if ls --color -d . &>/dev/null; then alias ls="ls --color=auto"; elif ls -G -d . &>/dev/null; then alias ls='ls -G'; fi
+alias lsblk="sudo lsblk"
+alias lshw="sudo lshw"
 alias lsof='sudo lsof'
 alias lspci='sudo lspci'
+alias lsusb="sudo lsusb"
+alias lvdisplay="sudo lvdisplay"
+alias make-kpkg="sudo make-kpkg"
+alias mkfs.ext4="sudo mkfs.ext4"
+alias mkfs="sudo mkfs"
 alias mkpasswd='sudo mkpasswd'
+alias modprobe="sudo modprobe"
+alias more='more -R'
 alias mount='sudo mount'
 alias mtr='sudo mtr'
 alias mv='sudo mv'
 alias mysql='sudo mysql'
 alias mysql_secure_installation='sudo mysql_secure_installation'
+alias mysql_upgrade="sudo mysql_upgrade"
+alias mysqld_safe="sudo mysqld_safe"
+alias mysqldump="sudo mysqldump"
 alias nc='sudo nc'
+alias ncat="sudo ncat"
 alias netfilter-persistent='sudo netfilter-persistent'
+alias netplan="sudo netplan"
 alias netstat='sudo netstat'
+alias networkctl="sudo networkctl"
 alias networking='sudo /etc/init.d/networking'
+alias networksetup='sudo networksetup'
+alias nginx="sudo nginx"
+alias ngrep="sudo ngrep"
+alias nield="sudo nield"
 alias nmap='sudo nmap'
 alias nmcli='sudo nmcli'
+alias nping="sudo nping"
 alias nslookup='sudo nslookup'
+alias oatom="open '${PYCHARM_OPTIONS}/atom-icon-associations.xml'"
+alias obrew="open '${BREWFILE}'"
+alias odeudas="brctl download '${NUMBERS}/Julia - Pension Deudas y Estimaciones Lido.numbers' && open '${NUMBERS}/Julia - Pension Deudas y Estimaciones Lido.numbers'"
+alias oduti="open '${FILES}/duti/developer.text'"
+alias ogem="open '${GEMFILE}'"
+alias ogithub="'${VISUAL}' '${REPOS}/CLONES/github.repos'"
+alias oj5pu="'${VISUAL}' '${REPOS}/HOME/${GITHUB_USERNAME}.repos'"
+alias olumenbiomics="'${VISUAL}' '${REPOS}/HOME/${GITHUB_ORGANIZATION}.repos'"
+alias onpm="open '${NPMFILE}'"
+alias openvpn="sudo openvpn"
+alias opip="open '${REQUIREMENTS}'"
+alias opkg="sudo opkg"
+alias opost="open '${JETBRAINS}/python.mio.postfixTemplates'"
+alias oreembolsos="brctl download '${NUMBERS}/Reembolsos.numbers' && open '${NUMBERS}/Reembolsos.numbers'"
+alias oufile="open '${USERFILE}'"
+alias parted="sudo parted"
+alias partprobe="sudo partprobe"
+alias partx="sudo partx"
+alias pecl="sudo pecl"
+alias pgrep="pgrep -i"
+alias phpdismod="sudo phpdismod"
+alias phpenmod="sudo phpenmod"
+alias ping="sudo ping"
+alias pkill="sudo pkill"
+alias play="ansible-playbook"
+alias pltobin="plutil -convert binary1" # This changes the plist in XML back to binary format
+alias pltoxml="plutil -convert xml1"    # This converts the existing binary plist file into XML format
+alias polo-disk="sudo polo-disk"
+alias postfix="sudo postfix"
+alias poweroff="sudo poweroff"
+alias pre-up="sudo pre-up"
+alias pvscan="sudo pvscan"
+alias qemu-nbd="sudo qemu-nbd"
 alias reboot='sudo reboot'
+alias remove="sudo apt remove"
 alias rkhunter='sudo rkhunter'
+alias rm="sudo rm -r"
+alias rmmod="sudo rmmod"
+alias rndc='sudo rndc'
 alias route='sudo route'
+alias rsync_d="rsync -v -a --delete-after --checksum"
+alias saved="test -d '${CACHES}/' && sudo rm -rf '${SAVED}/*' || echo 'error no saved'"
+alias scalecheck="rclone check --progress --s3-storage-class=GLACIER"
+alias scalecleanup="rclone cleanup --progress --s3-storage-class=GLACIER"
+alias scalecopy="rclone copy --progress --s3-storage-class=GLACIER"
+alias scaledelete="rclone delete --progress --s3-storage-class=GLACIER"
+alias scalels="rclone ls --progress --s3-storage-class=GLACIER scaleway:/"
+alias scalelsd="rclone lsd --progress --s3-storage-class=GLACIER scaleway:/"
+alias scalelsl="rclone lsl --progress --s3-storage-class=GLACIER scaleway:/"
+alias scalemkdir="rclone mkdir --progress --s3-storage-class=GLACIER"
+alias scalemove="rclone move --progress --s3-storage-class=GLACIER"
+alias scalepurge="rclone purge --progress --s3-storage-class=GLACIER"
+alias scalermdir="rclone rmdir --progress --s3-storage-class=GLACIER"
+alias scalermdirs="rclone rmdirs --progress --s3-storage-class=GLACIER"
+alias scalesize="rclone size --progress --s3-storage-class=GLACIER scaleway:/"
+alias scalesync="rclone sync --progress --s3-storage-class=GLACIER"
+alias scutil='sudo scutil'
+alias search="sudo apt-cache search"
 alias service='sudo service'
+alias shutdown="sudo shutdown --no-wall"
+alias sl=ls
 alias smartctl='sudo smartctl'
 alias software-properties-gtk='sudo software-properties-gtk'
+alias spctl="sudo spctl"
+alias spctl='sudo spctl'
+alias speedtest="wget -O /dev/null http://speed.transip.nl/100mb.bin"
 alias ss='sudo ss'
+alias startbackup="tmutil startbackup"
+alias swapoff="sudo swapoff"
+alias swapon='sudo swapon'
 alias sysctl='sudo sysctl'
 alias systemctl='sudo systemctl'
+alias systemd-analyze="sudo systemd-analyze"
 alias systemd-resolve='sudo systemd-resolve'
+alias sysupgrade='sudo sysupgrade'
 alias tasksel='sudo tasksel'
 alias tcpdump='sudo tcpdump'
+alias tcptraceroute='sudo traceroute'
 alias tcptrack='sudo tcptrack'
 alias telnet='sudo telnet'
 alias traceroute='sudo traceroute'
+alias trash='sudo trash'
+alias tree1="tree -d -L 1"
+alias tree2="tree -d -L 2"
+alias tree="tree -C" # Always use colored `tree` output
+alias treed="tree -d"
 alias udevadm='sudo udevadm'
 alias ufw='sudo ufw'
 alias umount='sudo umount'
 alias unbound-anchor='sudo unbound-anchor'
 alias unbound-host='sudo unbound-host'
 alias update-alternatives='sudo update-alternatives'
-alias update-grub='sudo update-grub'
 alias update-grub2='sudo update-grub2'
+alias update-grub='sudo update-grub'
+alias update-locale="sudo update-locale"
 alias update-manager='sudo update-manager'
 alias update-rc.d='sudo update-rc.d'
-alias usermod='sudo usermod'
-alias wg-quick='sudo wg-quick'
-alias whois='sudo whois'
-alias addgroup="sudo addgroup"
-alias chgrp="sudo chgrp"
-alias pre-up="sudo pre-up"
-alias a2enmod="sudo a2enmod"
-alias a2dismod="sudo a2dismod"
-alias phpenmod="sudo phpenmod"
-alias phpdismod="sudo phpdismod"
-alias apache2="sudo apache2"
-alias mysqldump="sudo mysqldump"
-alias pecl="sudo pecl"
-alias debconf="sudo debconf"
-alias networkctl="sudo networkctl"
-alias wg="sudo wg"
-alias modprobe="sudo modprobe"
-alias qemu-nbd="sudo qemu-nbd"
-alias partprobe="sudo partprobe"
-alias partx="sudo partx"
-alias vgscan="sudo vgscan"
-alias vgchange="sudo vgchange"
-alias lvdisplay="sudo lvdisplay"
-alias rmmod="sudo rmmod"
-alias losetup="sudo losetup"
-alias parted="sudo parted"
-alias lshw="sudo lshw"
-alias depmod="sudo depmod"
-alias zenmap="sudo zenmap"
-alias ncat="sudo ncat"
-alias nping="sudo nping"
-alias ping="sudo ping"
+alias update="sudo apt update"
+alias update="sudo softwareupdate -aiR" # Install all macOS updates and restart system
+[[ "$(uname -s)" == "Linux" ]] && alias updatedb='sudo updatedb'
+alias upgrade="sudo apt upgrade"
 alias useradd="sudo useradd"
-alias systemd-analyze="sudo systemd-analyze"
-alias ngrep="sudo ngrep"
-alias nield="sudo nield"
-alias flatpak="sudo flatpak"
-alias debuild="sudo debuild"
-alias make-kpkg="sudo make-kpkg"
-alias debi="sudo debi"
-alias dpkg-source="sudo dpkg-source"
-alias configure-debian="sudo configure-debian"
-alias apt-file="sudo apt-file"
-alias iptables_save='sudo iptables_save'
-alias mysql_upgrade="sudo mysql_upgrade"
-alias mysqld_safe="sudo mysqld_safe"
-alias cat="sudo cat"
-alias apt-all="sudo apt update -y; sudo apt upgrade -y; sudo apt dist-upgrade -y; sudo apt autoremove -y; sudo apt autoclean -y"
-alias more="sudo more"
-alias less="sudo less"
-alias pvscan="sudo pvscan"
-alias pkill="sudo pkill"
-alias hwclock="sudo hwclock"
-alias date="sudo date"
-alias mkfs="sudo mkfs"
-alias mkfs.ext4="sudo mkfs.ext4"
-alias automysqlbackup="sudo automysqlbackup"
-alias update-locale="sudo update-locale"
-alias deluser="sudo deluser"
-alias netplan="sudo netplan"
-alias delgroup="sudo delgroup"
-alias openvpn="sudo openvpn"
-alias nginx="sudo nginx"
-alias apt-add-repository="sudo apt-add-repository"
-alias poweroff="sudo poweroff"
-alias polo-disk="sudo polo-disk"
-alias cubic="sudo cubic"
-alias postfix="sudo postfix"
-alias debconf-set-selections="sudo debconf-set-selections"
-alias fdisk="sudo fdisk"
-alias lsblk="sudo lsblk"
-alias lsusb="sudo lsusb"
-alias opkg="sudo opkg"
-alias spctl="sudo spctl"
-alias scutil="sudo scutil"
-alias kextload="sudo kextload"
-
-## TMUTIL
-alias backups="tmutil listbackups"
-alias latest="tmutil latestbackup"
-alias startbackup="tmutil startbackup"
-
-## TREE
-alias tree="tree -C" # Always use colored `tree` output
-alias treed="tree -d"
-alias tree1="tree -d -L 1"
-alias tree2="tree -d -L 2"
-
-## VI
-if command -v vim >/dev/null 2>&1; then
-  alias vi=vim
-else
-  alias vim=vi
-fi
+alias usermod='sudo usermod'
+if command -v vim >/dev/null 2>&1; then alias vi=vim; else alias vim=vi; fi
+alias vgchange="sudo vgchange"
+alias vgscan="sudo vgscan"
+alias wg-quick='sudo wg-quick'
+alias wg="sudo wg"
+alias whois='sudo whois'
+alias wpa_passphrase='sudo wpa_passphrase'
+alias wpa_supplicant='sudo wpa_supplicant'
+alias xattr='sudo xattr'
+alias zenmap="sudo zenmap"
