Bump version: 0.1.135 → 0.1.136

diff --git a/bashrc/scripts/bashrc-functions b/bashrc/scripts/bashrc-functions
--- a/bashrc/scripts/bashrc-functions
+++ b/bashrc/scripts/bashrc-functions
@@ -148,18 +148,21 @@ function chownaz() {
   sudo chmod -R u+r [a-z,A-Z,0-9]* .[a-z,A-Z,0-9]*
 }
 
-#function command_not_found_handle() {
-#  if [[ -x /usr/lib/command-not-found ]]; then
-#    /usr/lib/command-not-found -- "$1"
-#    return $?
-#  elif [[ -x /usr/share/command-not-found/command-not-found ]]; then
-#    /usr/share/command-not-found/command-not-found -- "$1"
-#    return $?
-#  else
-#    printf "%s: command not found\n" "$1" >&2
-#    return 127
-#  fi
-#}
+
+function command_not_found_handle() {
+  if ! test -n "${DARWIN}"; then
+    if [[ -x /usr/lib/command-not-found ]]; then
+      /usr/lib/command-not-found -- "$1"
+      return $?
+    elif [[ -x /usr/share/command-not-found/command-not-found ]]; then
+      /usr/share/command-not-found/command-not-found -- "$1"
+      return $?
+    else
+      printf "%s: command not found\n" "$1" >&2
+      return 127
+    fi
+  fi
+}
 
 function cleandir() {
   [[ "$(ls -A "${1}"/* >/dev/null 2>&1)" ]] || sudo "${RM_PATH}" -rf "${1}"/*
